services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fast-api-server
    ports:
      - "5001:5000"
    environment:
      DATABASE_HOST: db # this is the name of the database container
      DATABASE_NAME: mydb
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client-web
    ports:
      # port forwarding 80001 to 80
      - "8001:80"
    depends_on:
      - server

volumes:
  postgres_data:
